### ISSUE TITLE
pip build crashes on deploy

### ISSUE THREAD

**Issue by bradleybuda** [heroku/heroku-connect-skeleton#7]
I'm seeing this error in the build log after clicking the Heroku button and typing in my app name (no additional changes or customizations):

```
-----> Installing requirements with pip
       Collecting Flask==0.10.1 (from -r /tmp/build_e24c5ecebe282632c6ab43c95fbe517d/heroku-heroku-connect-quickstart-a5ff4c4/requirements.txt (line 1))
         Downloading Flask-0.10.1.tar.gz (544kB)
       Collecting Jinja2==2.7.3 (from -r /tmp/build_e24c5ecebe282632c6ab43c95fbe517d/heroku-heroku-connect-quickstart-a5ff4c4/requirements.txt (line 2))
         Downloading Jinja2-2.7.3.tar.gz (378kB)
       Collecting MarkupSafe==0.23 (from -r /tmp/build_e24c5ecebe282632c6ab43c95fbe517d/heroku-heroku-connect-quickstart-a5ff4c4/requirements.txt (line 3))
         Downloading MarkupSafe-0.23.tar.gz
       Collecting Werkzeug==0.10.1 (from -r /tmp/build_e24c5ecebe282632c6ab43c95fbe517d/heroku-heroku-connect-quickstart-a5ff4c4/requirements.txt (line 4))
         Downloading Werkzeug-0.10.1.tar.gz (1.1MB)
       Collecting itsdangerous==0.24 (from -r /tmp/build_e24c5ecebe282632c6ab43c95fbe517d/heroku-heroku-connect-quickstart-a5ff4c4/requirements.txt (line 5))
         Downloading itsdangerous-0.24.tar.gz (46kB)
       Collecting wsgiref==0.1.2 (from -r /tmp/build_e24c5ecebe282632c6ab43c95fbe517d/heroku-heroku-connect-quickstart-a5ff4c4/requirements.txt (line 6))
         Downloading wsgiref-0.1.2.zip
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-d3x8j44n/wsgiref/setup.py", line 5, in <module>
               import ez_setup
             File "/tmp/pip-build-d3x8j44n/wsgiref/ez_setup/__init__.py", line 170
               print "Setuptools version",version,"or greater has been installed."
                                        ^
           SyntaxError: Missing parentheses in call to 'print'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d3x8j44n/wsgiref/
```

**Comment by renatoliveira** [comment]
Just tried to deploy this as well, got the same error. How come this isn't fixed yet? 😢

**Comment by slant** [comment]
Just to break the unintended radio silence - per the in-line updates in this issue, we've got a fix for this put together that should be going out soon.
